defaults:
  - _self_
  - data: default
  - model: default
  - trainer: default
  - experiment: null

seed: 42
project_name: "dl-research"
experiment_name: "EXP_DEFAULT"

output_dir: "outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}"

hydra:
  run:
    dir: ${output_dir}
