#!/usr/bin/env python3
"""
Literature index generator.

Scans experiments for paper citations and builds a reverse index.
Citations use format: [@paper_key]

Usage:
    python scripts/lit_index.py
    python scripts/lit_index.py --check  # Validate only, no write
"""
import os
import re
import yaml
import argparse
from pathlib import Path
from collections import defaultdict


def load_papers(path: str = "literature/papers.yaml") -> dict:
    """Load paper database."""
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        return yaml.safe_load(f) or {}


def find_citations(text: str) -> list[str]:
    """Extract [@key] citations from text."""
    return re.findall(r'\[@(\w+)\]', text)


def scan_experiments() -> dict[str, list[str]]:
    """Scan all experiment READMEs for citations.
    
    Returns: {experiment_id: [paper_keys]}
    """
    citations = {}
    exp_dir = Path("experiments")
    
    if not exp_dir.exists():
        return citations
    
    for readme in exp_dir.glob("*/README.md"):
        exp_id = readme.parent.name
        content = readme.read_text()
        refs = find_citations(content)
        if refs:
            citations[exp_id] = refs
    
    return citations


def build_reverse_index(citations: dict[str, list[str]]) -> dict[str, list[str]]:
    """Build paper → experiments mapping."""
    index = defaultdict(list)
    for exp_id, papers in citations.items():
        for paper in papers:
            index[paper].append(exp_id)
    return dict(index)


def generate_report(papers: dict, citations: dict, reverse_index: dict) -> str:
    """Generate markdown report."""
    lines = ["# Literature Index", "", "*Auto-generated by `scripts/lit_index.py`*", ""]
    
    # Stats
    total_papers = len(papers)
    cited_papers = len(reverse_index)
    total_exps = len(citations)
    
    lines.append(f"**Papers:** {total_papers} in database, {cited_papers} cited")
    lines.append(f"**Experiments:** {total_exps} with citations")
    lines.append("")
    
    # Reverse index: papers → experiments
    lines.append("## Papers → Experiments")
    lines.append("")
    
    if reverse_index:
        lines.append("| Paper | Experiments |")
        lines.append("|-------|-------------|")
        for paper, exps in sorted(reverse_index.items()):
            paper_info = papers.get(paper, {})
            title = paper_info.get("title", paper)
            exp_list = ", ".join(sorted(exps))
            lines.append(f"| **{paper}**: {title[:40]}{'...' if len(title) > 40 else ''} | {exp_list} |")
    else:
        lines.append("*No citations found in experiments.*")
    
    lines.append("")
    
    # Orphan papers (in database but never cited)
    all_cited = set(reverse_index.keys())
    all_papers = set(papers.keys())
    orphans = all_papers - all_cited
    
    if orphans:
        lines.append("## Uncited Papers")
        lines.append("")
        lines.append("Papers in database but not referenced by any experiment:")
        lines.append("")
        for key in sorted(orphans):
            info = papers[key]
            lines.append(f"- `{key}`: {info.get('title', 'No title')}")
        lines.append("")
    
    # Missing papers (cited but not in database)
    all_refs = set()
    for refs in citations.values():
        all_refs.update(refs)
    missing = all_refs - all_papers
    
    if missing:
        lines.append("## ⚠️ Missing Papers")
        lines.append("")
        lines.append("Referenced in experiments but not in `papers.yaml`:")
        lines.append("")
        for key in sorted(missing):
            exps = reverse_index.get(key, [])
            lines.append(f"- `{key}` (used in: {', '.join(exps)})")
        lines.append("")
    
    # Experiments → papers
    lines.append("## Experiments → Papers")
    lines.append("")
    
    if citations:
        for exp_id, refs in sorted(citations.items()):
            lines.append(f"### {exp_id}")
            for ref in refs:
                info = papers.get(ref, {})
                title = info.get("title", "Unknown")
                lines.append(f"- [@{ref}] {title}")
            lines.append("")
    else:
        lines.append("*No experiments have citations yet.*")
    
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate literature index")
    parser.add_argument("--check", action="store_true", help="Validate only, don't write")
    parser.add_argument("--output", "-o", default="literature/index.md", help="Output file")
    args = parser.parse_args()
    
    papers = load_papers()
    citations = scan_experiments()
    reverse_index = build_reverse_index(citations)
    
    report = generate_report(papers, citations, reverse_index)
    
    if args.check:
        print(report)
        # Check for missing papers
        all_refs = set()
        for refs in citations.values():
            all_refs.update(refs)
        missing = all_refs - set(papers.keys())
        if missing:
            print(f"\n⚠️  Missing papers: {missing}")
            exit(1)
    else:
        Path(args.output).write_text(report)
        print(f"✓ Generated {args.output}")
        print(f"  Papers: {len(papers)} | Cited: {len(reverse_index)} | Experiments: {len(citations)}")


if __name__ == "__main__":
    main()
